name: life-manager-docker

# version: '3.8'

services:
  user:
    build:
      context: .
      dockerfile: user.dockerfile # Specify the Dockerfile for the frontend
    ports:
      - '4200:80' # Map container port 80 to host port 80

  server:
    build:
      context: .
      dockerfile: server.dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  # double check this
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lifemanager

    volumes:
      - postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - user
      - server

volumes:
  postgres-data:
